variables:
  IMAGE_NAME: raziels/flask-app
  IMAGE_TAG: python-app-1.0

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install -y python3-pip git gcc python3-dev
    # Install any other dependencies needed for testing here
    - pip3 install -r src/requirements.txt
  script:
    - python3 -m pytest -v src/app/tests

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker push "$IMAGE_NAME:$IMAGE_TAG"

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$AWS_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
  script:
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$AWS_USERNAME@$AWS_PUBLIC_IP" "
        echo $REGISTRY_PASS | docker login -u $REGISTRY_USER --password-stdin &&
        docker stop \$(docker ps -q --filter 'publish=5000') || echo 'No containers to stop' &&
        docker rm -f \$(docker ps -aq --filter 'publish=5000') || echo 'No containers to remove' &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"